### PR TITLE
Fix: #34 useNativeDriver default to false

### PR DESCRIPTION
**Pull request by justJay-dev**
hey there! Finally got my local working. 

Included here is just a simple change to move everything using Animated.timing to useNativeDriver false, it looks like you had started to parse out some logic based on platform, but I am not privvy to what your aims are there, safer to default to false given you had some expressly set false prior to this change. 

Cheers!

### CODE REVIEW

**Comment by justJay-dev** [comment]
Hey just checking in, are we good to merge this?

**Comment by yamankatby** [comment]
Hey @justJay-dev,
Very sorry for not having time to actively maintain this repo. I'll find time to merge this PR later this week.

btw, I can add you as a collaborator, so you own a part of the repo. It'll be a super great help if you have time. Just tell me if you want.

**Comment by pigpudle** [comment]
Can you please merge it?

**Comment by yamankatby** [comment]
Hi there,
Just merged, soon to npm 🙌

**Comment by souzaluiz** [comment]
still happening in version 1.3.7

**Pull request merged**
